### ISSUE TITLE
Helm-Chart does not support SecurityContext anymore

### ISSUE THREAD

**Issue by gilberts42** [mongodb/mongodb-kubernetes#168]
**What did you do to encounter the bug?**

Install mongodb-kubernetes 1.1.0 via helm chart from https://mongodb.github.io/helm-charts

**What did you expect?**

I need to provide a Security Context as I did with CommunityOperator. The same value is not used anymore to create the deployment:

```
operator:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
 ```

**What happened instead?**
It is not possible to set the container securityContext anymore.

**Operator Information**
 - mongodb-kubernetes 1.1.0

**Kubernetes Cluster Information**
Using RKE2 Cluster with CIS Profile enabled.
