### ISSUE TITLE
Ops Manager disables JVM Container support, always uses 4608MB for JVM heap

### ISSUE THREAD

**Issue by fhoekstra** [mongodb/mongodb-kubernetes#194]
**What did you do to encounter the bug?**
1. Deploy Ops Manager in Kubernetes using the operator with default configuration, and 0 databases, no load whatsoever.
2. Limit memory to less than 4GB
3. It won't start, OOM killed
4. Set memory requests and limits to 5GB
5. Observe misconfiguration of Ops Manager

**What did you expect?**
For the Java app to respect the resource requests and limits as specified for the deployment.
See for example:

https://www.ibm.com/docs/en/sdk-java-technology/8?topic=options-xx-usecontainersupport
https://learn.microsoft.com/en-us/azure/developer/java/containers/overview#determine-jvm-heap-memory

**What happened instead?**
In the spec of the pod that runs Ops Manager, I find:
```yaml
spec.containers[0].env:
 [...]
  - name: CUSTOM_JAVA_MMS_UI_OPTS
    value: -Xmx4608m -Xms4608m
  - name: CUSTOM_JAVA_DAEMON_OPTS
     value: -Xmx4608m -Xms4608m -DDAEMON.DEBUG.PORT=8090
```
I did not specify these values, and this means the JVM does not respect memory limits and instead **always allocates 4608 MB for the JVM heap**. Default behavior of the JVM is to respect limits. If you remove these args from the Ops Manager image, that would allow customers to size their Ops Manager deployments appropriately for their workload.

**Operator Information**
 - Operator Version: 1.0.1
 - Ops Manager version: quay.io/mongodb/mongodb-enterprise-ops-manager-ubi@sha256:379479f479c82af27eae25e798da6d537ede820142c21239ee926f595c93fca1

**Kubernetes Cluster Information**
 - OpenShift
 - 1.31.8
 - quay
